on:
  push:
    branches:
      - master
    issues:
      types: [closed]
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    name: updates top-ranking issues issue
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: python main.py ${{ secrets.GITHUB_TOKEN }}
